using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Unified.Db.Migrations;

/// <inheritdoc />
[DbContext(typeof(UnifiedDbContext))]
[Migration("20260703190000_AddSchedulingAssignments")]
public partial class AddSchedulingAssignments : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE "AssignmentCategoryTypes" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1) PRIMARY KEY,
                "Code" character varying(50) NOT NULL,
                "Description" character varying(100) NOT NULL,
                "EffectiveDate" timestamp with time zone NOT NULL,
                "ExpiryDate" timestamp with time zone NULL,
                "CreatedById" uuid NULL,
                "CreatedOn" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedById" uuid NULL,
                "UpdatedOn" timestamp with time zone NULL,
                CONSTRAINT "FK_AssignmentCategoryTypes_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_AssignmentCategoryTypes_Users_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL
            );
            CREATE UNIQUE INDEX "IX_AssignmentCategoryTypes_Code" ON "AssignmentCategoryTypes" ("Code");
            CREATE INDEX "IX_AssignmentCategoryTypes_CreatedById" ON "AssignmentCategoryTypes" ("CreatedById");
            CREATE INDEX "IX_AssignmentCategoryTypes_UpdatedById" ON "AssignmentCategoryTypes" ("UpdatedById");

            CREATE TABLE "AssignmentSubCategoryTypes" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1) PRIMARY KEY,
                "Code" character varying(50) NOT NULL,
                "Description" character varying(100) NOT NULL,
                "EffectiveDate" timestamp with time zone NOT NULL,
                "ExpiryDate" timestamp with time zone NULL,
                "CreatedById" uuid NULL,
                "CreatedOn" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedById" uuid NULL,
                "UpdatedOn" timestamp with time zone NULL,
                CONSTRAINT "FK_AssignmentSubCategoryTypes_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_AssignmentSubCategoryTypes_Users_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL
            );
            CREATE UNIQUE INDEX "IX_AssignmentSubCategoryTypes_Code" ON "AssignmentSubCategoryTypes" ("Code");
            CREATE INDEX "IX_AssignmentSubCategoryTypes_CreatedById" ON "AssignmentSubCategoryTypes" ("CreatedById");
            CREATE INDEX "IX_AssignmentSubCategoryTypes_UpdatedById" ON "AssignmentSubCategoryTypes" ("UpdatedById");

            CREATE TABLE "AssignmentTypes" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1) PRIMARY KEY,
                "LocationId" integer NOT NULL,
                "Code" character varying(50) NOT NULL,
                "Description" character varying(100) NOT NULL,
                "EffectiveDate" timestamp with time zone NOT NULL,
                "ExpiryDate" timestamp with time zone NULL,
                "CreatedById" uuid NULL,
                "CreatedOn" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedById" uuid NULL,
                "UpdatedOn" timestamp with time zone NULL,
                CONSTRAINT "FK_AssignmentTypes_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES "Locations" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_AssignmentTypes_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_AssignmentTypes_Users_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL
            );
            CREATE UNIQUE INDEX "IX_AssignmentTypes_LocationId_Code" ON "AssignmentTypes" ("LocationId", "Code");
            CREATE INDEX "IX_AssignmentTypes_CreatedById" ON "AssignmentTypes" ("CreatedById");
            CREATE INDEX "IX_AssignmentTypes_LocationId" ON "AssignmentTypes" ("LocationId");
            CREATE INDEX "IX_AssignmentTypes_UpdatedById" ON "AssignmentTypes" ("UpdatedById");

            CREATE TABLE "AssignmentSeries" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1) PRIMARY KEY,
                "EventSeriesId" integer NOT NULL,
                "AssignmentCategoryTypeId" integer NOT NULL,
                "AssignmentSubCategoryTypeId" integer NOT NULL,
                "AssignmentTypeId" integer NOT NULL,
                "Capacity" integer NOT NULL,
                "CreatedById" uuid NULL,
                "CreatedOn" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedById" uuid NULL,
                "UpdatedOn" timestamp with time zone NULL,
                CONSTRAINT "CK_AssignmentSeries_CapacityAtLeastOne" CHECK ("Capacity" >= 1),
                CONSTRAINT "FK_AssignmentSeries_EventSeries_EventSeriesId" FOREIGN KEY ("EventSeriesId") REFERENCES "EventSeries" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_AssignmentSeries_AssignmentCategoryTypes_AssignmentCategoryTypeId" FOREIGN KEY ("AssignmentCategoryTypeId") REFERENCES "AssignmentCategoryTypes" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_AssignmentSeries_AssignmentSubCategoryTypes_AssignmentSubCategoryTypeId" FOREIGN KEY ("AssignmentSubCategoryTypeId") REFERENCES "AssignmentSubCategoryTypes" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_AssignmentSeries_AssignmentTypes_AssignmentTypeId" FOREIGN KEY ("AssignmentTypeId") REFERENCES "AssignmentTypes" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_AssignmentSeries_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_AssignmentSeries_Users_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL
            );
            CREATE UNIQUE INDEX "IX_AssignmentSeries_EventSeriesId" ON "AssignmentSeries" ("EventSeriesId");
            CREATE INDEX "IX_AssignmentSeries_AssignmentCategoryTypeId" ON "AssignmentSeries" ("AssignmentCategoryTypeId");
            CREATE INDEX "IX_AssignmentSeries_AssignmentSubCategoryTypeId" ON "AssignmentSeries" ("AssignmentSubCategoryTypeId");
            CREATE INDEX "IX_AssignmentSeries_AssignmentTypeId" ON "AssignmentSeries" ("AssignmentTypeId");
            CREATE INDEX "IX_AssignmentSeries_CreatedById" ON "AssignmentSeries" ("CreatedById");
            CREATE INDEX "IX_AssignmentSeries_UpdatedById" ON "AssignmentSeries" ("UpdatedById");

            CREATE TABLE "AssignmentEntries" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1) PRIMARY KEY,
                "AssignmentSeriesId" integer NULL,
                "EventId" integer NOT NULL,
                "AssignmentCategoryTypeId" integer NOT NULL,
                "AssignmentSubCategoryTypeId" integer NOT NULL,
                "AssignmentTypeId" integer NOT NULL,
                "Capacity" integer NOT NULL,
                "CreatedById" uuid NULL,
                "CreatedOn" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedById" uuid NULL,
                "UpdatedOn" timestamp with time zone NULL,
                CONSTRAINT "CK_AssignmentEntries_CapacityAtLeastOne" CHECK ("Capacity" >= 1),
                CONSTRAINT "FK_AssignmentEntries_AssignmentSeries_AssignmentSeriesId" FOREIGN KEY ("AssignmentSeriesId") REFERENCES "AssignmentSeries" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_AssignmentEntries_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_AssignmentEntries_AssignmentCategoryTypes_AssignmentCategoryTypeId" FOREIGN KEY ("AssignmentCategoryTypeId") REFERENCES "AssignmentCategoryTypes" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_AssignmentEntries_AssignmentSubCategoryTypes_AssignmentSubCategoryTypeId" FOREIGN KEY ("AssignmentSubCategoryTypeId") REFERENCES "AssignmentSubCategoryTypes" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_AssignmentEntries_AssignmentTypes_AssignmentTypeId" FOREIGN KEY ("AssignmentTypeId") REFERENCES "AssignmentTypes" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_AssignmentEntries_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_AssignmentEntries_Users_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL
            );
            CREATE INDEX "IX_AssignmentEntries_AssignmentSeriesId" ON "AssignmentEntries" ("AssignmentSeriesId");
            CREATE UNIQUE INDEX "IX_AssignmentEntries_EventId" ON "AssignmentEntries" ("EventId");
            CREATE INDEX "IX_AssignmentEntries_AssignmentCategoryTypeId" ON "AssignmentEntries" ("AssignmentCategoryTypeId");
            CREATE INDEX "IX_AssignmentEntries_AssignmentSubCategoryTypeId" ON "AssignmentEntries" ("AssignmentSubCategoryTypeId");
            CREATE INDEX "IX_AssignmentEntries_AssignmentTypeId" ON "AssignmentEntries" ("AssignmentTypeId");
            CREATE INDEX "IX_AssignmentEntries_CreatedById" ON "AssignmentEntries" ("CreatedById");
            CREATE INDEX "IX_AssignmentEntries_UpdatedById" ON "AssignmentEntries" ("UpdatedById");

            CREATE TABLE "ShiftAssignmentEntries" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1) PRIMARY KEY,
                "ShiftEntryId" integer NOT NULL,
                "AssignmentEntryId" integer NOT NULL,
                "CreatedById" uuid NULL,
                "CreatedOn" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedById" uuid NULL,
                "UpdatedOn" timestamp with time zone NULL,
                CONSTRAINT "FK_ShiftAssignmentEntries_ShiftEntries_ShiftEntryId" FOREIGN KEY ("ShiftEntryId") REFERENCES "ShiftEntries" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_ShiftAssignmentEntries_AssignmentEntries_AssignmentEntryId" FOREIGN KEY ("AssignmentEntryId") REFERENCES "AssignmentEntries" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_ShiftAssignmentEntries_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_ShiftAssignmentEntries_Users_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL
            );
            CREATE INDEX "IX_ShiftAssignmentEntries_ShiftEntryId" ON "ShiftAssignmentEntries" ("ShiftEntryId");
            CREATE INDEX "IX_ShiftAssignmentEntries_AssignmentEntryId" ON "ShiftAssignmentEntries" ("AssignmentEntryId");
            CREATE UNIQUE INDEX "IX_ShiftAssignmentEntries_ShiftEntryId_AssignmentEntryId" ON "ShiftAssignmentEntries" ("ShiftEntryId", "AssignmentEntryId");
            CREATE INDEX "IX_ShiftAssignmentEntries_CreatedById" ON "ShiftAssignmentEntries" ("CreatedById");
            CREATE INDEX "IX_ShiftAssignmentEntries_UpdatedById" ON "ShiftAssignmentEntries" ("UpdatedById");

            CREATE TABLE "ShiftAssignmentEntryUsers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1) PRIMARY KEY,
                "ShiftAssignmentEntryId" integer NOT NULL,
                "UserId" uuid NOT NULL,
                "CreatedById" uuid NULL,
                "CreatedOn" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedById" uuid NULL,
                "UpdatedOn" timestamp with time zone NULL,
                CONSTRAINT "FK_ShiftAssignmentEntryUsers_ShiftAssignmentEntries_ShiftAssignmentEntryId" FOREIGN KEY ("ShiftAssignmentEntryId") REFERENCES "ShiftAssignmentEntries" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_ShiftAssignmentEntryUsers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_ShiftAssignmentEntryUsers_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_ShiftAssignmentEntryUsers_Users_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL
            );
            CREATE INDEX "IX_ShiftAssignmentEntryUsers_ShiftAssignmentEntryId" ON "ShiftAssignmentEntryUsers" ("ShiftAssignmentEntryId");
            CREATE INDEX "IX_ShiftAssignmentEntryUsers_UserId" ON "ShiftAssignmentEntryUsers" ("UserId");
            CREATE UNIQUE INDEX "IX_ShiftAssignmentEntryUsers_ShiftAssignmentEntryId_UserId" ON "ShiftAssignmentEntryUsers" ("ShiftAssignmentEntryId", "UserId");
            CREATE INDEX "IX_ShiftAssignmentEntryUsers_CreatedById" ON "ShiftAssignmentEntryUsers" ("CreatedById");
            CREATE INDEX "IX_ShiftAssignmentEntryUsers_UpdatedById" ON "ShiftAssignmentEntryUsers" ("UpdatedById");
            """
        );
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP TABLE IF EXISTS "ShiftAssignmentEntryUsers";
            DROP TABLE IF EXISTS "ShiftAssignmentEntries";
            DROP TABLE IF EXISTS "AssignmentEntries";
            DROP TABLE IF EXISTS "AssignmentSeries";
            DROP TABLE IF EXISTS "AssignmentTypes";
            DROP TABLE IF EXISTS "AssignmentSubCategoryTypes";
            DROP TABLE IF EXISTS "AssignmentCategoryTypes";
            """
        );
    }
}
