<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.1" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\db\db.csproj" />
    <ProjectReference Include="..\Unified.Authorization\Unified.Authorization.csproj" />
    <ProjectReference Include="..\Unified.Calendar\Unified.Calendar.csproj" />
    <ProjectReference Include="..\Unified.Stats\Unified.Stats.csproj" />
  </ItemGroup>
</Project>
