-- Mock BIPRDZ destination generated from the BCSS_Table_Mapping worksheet in
-- BCSS Tables and Fields (Historic Mapping) CURRENT_20260916.xlsx.
WHENEVER SQLERROR EXIT SQL.SQLCODE
alter session set container = freepdb1;

declare
   v_charset    varchar2(128);
   v_compatible varchar2(128);
   v_major      number;
   v_minor      number;
   v_user_count number;
begin
   select value
     into v_charset
     from nls_database_parameters
    where parameter = 'NLS_CHARACTERSET';

   select value
     into v_compatible
     from v$parameter
    where name = 'compatible';

   v_major := to_number ( regexp_substr(
      v_compatible,
      '^[0-9]+'
   ) );
   v_minor := to_number ( regexp_substr(
      v_compatible,
      '[0-9]+',
      1,
      2
   ) );
   if v_charset <> 'AL32UTF8' then
      raise_application_error(
         -20001,
         'BIPRDZ mock requires AL32UTF8'
      );
   end if;
   if v_major < 12
   or (
      v_major = 12
      and v_minor < 2
   ) then
      raise_application_error(
         -20002,
         'BIPRDZ mock requires COMPATIBLE >= 12.2'
      );
   end if;

   select count(*)
     into v_user_count
     from dba_users
    where username = 'COURTS';
   if v_user_count <> 1 then
      raise_application_error(
         -20003,
         'COURTS must exist in FREEPDB1'
      );
   end if;
end;
/

create table courts.sheriff_srvces (
   crt_loc_id              number(6),
   month                   date,
   scv_jy_shrf_hrs         number(10,2),
   scv_nj_shrf_hrs         number(10,2),
   scr_jy_shrf_hrs         number(10,2),
   scr_nj_shrf_hrs         number(10,2),
   scvf_shrf_hrs           number(10,2),
   pcra_shrf_hrs           number(10,2),
   pcvs_shrf_hrs           number(10,2),
   pcvf_shrf_hrs           number(10,2),
   pcry_shrf_hrs           number(10,2),
   crnr_shrf_hrs           number(10,2),
   othr_shrf_hrs           number(10,2),
   grd_shrf_hrs            number(10,2),
   grd_km_travl            number(6),
   grd_amal_cnt            number(6),
   grd_afem_cnt            number(6),
   grd_ymal_cnt            number(6),
   grd_yfem_cnt            number(6),
   air_shrf_hrs            number(10,2),
   air_amal_cnt            number(6),
   air_afem_cnt            number(6),
   air_ymal_cnt            number(6),
   air_yfem_cnt            number(6),
   hld_shrf_hrs            number(10,2),
   hld_cell_hrs            number(10,2),
   hld_amal_cnt            number(6),
   hld_afem_cnt            number(6),
   hld_ymal_cnt            number(6),
   hld_yfem_cnt            number(6),
   jry_shrf_hrs            number(10,2),
   jurors_paid             float(126),
   jurors_sumd             float(126),
   fam_war_hrs             number(10,2),
   fam_war_recd            number(6),
   fam_ord_hrs             number(10,2),
   fam_ord_recd            number(6),
   cvl_war_hrs             number(10,2),
   cvl_war_recd            number(6),
   cvl_exe_hrs             number(10,2),
   cvl_exe_recd            number(6),
   cvl_doc_hrs             number(10,2),
   cvl_doc_recd            number(6),
   ncv_doc_hrs             number(10,2),
   ncv_doc_recd            number(6),
   fam_doc_hrs             number(10,2),
   fam_doc_recd            number(6),
   drvr_plat_sus_hrs       number(10,2),
   drvr_sus_recd           number(8),
   plat_sus_recd           number(8),
   create_date             date,
   created_by              varchar2(30 byte),
   update_date             date,
   updated_by              varchar2(30 byte),
   nil_report              varchar2(1 byte),
   rvr_shrf_hrs            number(10,2),
   pcrtc_shrf_hrs          number(10,2),
   grd_lvl1_cnt            number(6),
   grd_lvl2_cnt            number(6),
   air_lvl1_cnt            number(6),
   air_lvl2_cnt            number(6),
   supervisor_yn           varchar2(1 byte),
   ca_reg_hrs              number(10,2),
   ca_hsm_hrs              number(10,2),
   scv_jy_hsm_hrs          number(10,2),
   scv_delib_hrs           number(10,2),
   scv_delib_hsm_hrs       number(10,2),
   scv_nj_hsm_hrs          number(10,2),
   scr_jy_hsm_hrs          number(10,2),
   scr_delib_hrs           number(10,2),
   scr_delib_hsm_hrs       number(10,2),
   scr_nj_hsm_hrs          number(10,2),
   scvf_hsm_hrs            number(10,2),
   pcvf_hsm_hrs            number(10,2),
   pcvs_hsm_hrs            number(10,2),
   pcra_hsm_hrs            number(10,2),
   pcry_hsm_hrs            number(10,2),
   othr_hsm_hrs            number(10,2),
   rvr_hsm_hrs             number(10,2),
   sg_staff_hrs            number(10,2),
   sg_hsm_hrs              number(10,2),
   crnr_hsm_hrs            number(10,2),
   vc_staff_hrs            number(10,2),
   vc_hsm_hrs              number(10,2),
   seg_amal_cnt            number(6),
   seg_ymal_cnt            number(6),
   fed_amal_cnt            number(6),
   fed_seg_amal_cnt        number(6),
   seg_afem_cnt            number(6),
   seg_yfem_cnt            number(6),
   fed_afem_cnt            number(6),
   fed_seg_afem_cnt        number(6),
   grd_amal_cnt_l1         number(6),
   grd_amal_cnt_l2         number(6),
   grd_amal_cnt_l3         number(6),
   grd_amal_cnt_seg_pc     number(6),
   air_amal_cnt_l1         number(6),
   air_amal_cnt_l2         number(6),
   air_amal_cnt_l3         number(6),
   air_amal_cnt_seg_pc     number(6),
   grd_ymal_cnt_l1         number(6),
   grd_ymal_cnt_l2         number(6),
   grd_ymal_cnt_l3         number(6),
   grd_ymal_cnt_seg_pc     number(6),
   air_ymal_cnt_l1         number(6),
   air_ymal_cnt_l2         number(6),
   air_ymal_cnt_l3         number(6),
   air_ymal_cnt_seg_pc     number(6),
   grd_fmal_cnt_l1         number(6),
   grd_fmal_cnt_l2         number(6),
   grd_fmal_cnt_l3         number(6),
   grd_fmal_cnt_seg_pc     number(6),
   air_fmal_cnt_l1         number(6),
   air_fmal_cnt_l2         number(6),
   air_fmal_cnt_l3         number(6),
   air_fmal_cnt_seg_pc     number(6),
   grd_afem_cnt_l1         number(6),
   grd_afem_cnt_l2         number(6),
   grd_afem_cnt_l3         number(6),
   grd_afem_cnt_seg_pc     number(6),
   air_afem_cnt_l1         number(6),
   air_afem_cnt_l2         number(6),
   air_afem_cnt_l3         number(6),
   air_afem_cnt_seg_pc     number(6),
   grd_yfem_cnt_l1         number(6),
   grd_yfem_cnt_l2         number(6),
   grd_yfem_cnt_l3         number(6),
   grd_yfem_cnt_seg_pc     number(6),
   air_yfem_cnt_l1         number(6),
   air_yfem_cnt_l2         number(6),
   air_yfem_cnt_l3         number(6),
   air_yfem_cnt_seg_pc     number(6),
   grd_ffem_cnt_l1         number(6),
   grd_ffem_cnt_l2         number(6),
   grd_ffem_cnt_l3         number(6),
   grd_ffem_cnt_seg_pc     number(6),
   air_ffem_cnt_l1         number(6),
   air_ffem_cnt_l2         number(6),
   air_ffem_cnt_l3         number(6),
   air_ffem_cnt_seg_pc     number(6),
   grd_esc_hrs_l1          number(10,2),
   grd_esc_hrs_l2          number(10,2),
   grd_esc_hrs_l3          number(10,2),
   grd_esc_trips_l1        number(6),
   grd_esc_trips_l2        number(6),
   grd_esc_trips_l3        number(6),
   grd_esc_kms_l1          number(6),
   grd_esc_kms_l2          number(6),
   grd_esc_kms_l3          number(6),
   air_esc_hrs_l1          number(10,2),
   air_esc_hrs_l2          number(10,2),
   air_esc_hrs_l3          number(10,2),
   air_esc_trips_l1        number(6),
   air_esc_trips_l2        number(6),
   air_esc_trips_l3        number(6),
   ccrt_hrs                number(10,2),
   ccrt_trips_cnt          number(6),
   ccrt_kms                number(6),
   jurors_panels_cnt       number(6),
   jurors_paid_sum         number(10,2),
   cvf_warr_rcvd           number(6),
   cvf_crtord_rcvd         number(6),
   cvf_docs_rcvd           number(6),
   cvf_othr_rcvd           number(6),
   cvf_warr_conc           number(6),
   cvf_crtord_conc         number(6),
   cvf_docs_conc           number(6),
   cvf_othr_conc           number(6),
   cvf_warr_hrs            number(10,2),
   cvf_crtord_hrs          number(10,2),
   cvf_docs_hrs            number(10,2),
   cvf_othr_hrs            number(10,2),
   crim_warr_rcvd          number(6),
   crim_crtord_rcvd        number(6),
   crim_docs_rcvd          number(6),
   crim_othr_rcvd          number(6),
   crim_warr_conc          number(6),
   crim_crtord_conc        number(6),
   crim_docs_conc          number(6),
   crim_othr_conc          number(6),
   crim_warr_hrs           number(10,2),
   crim_crtord_hrs         number(10,2),
   crim_docs_hrs           number(10,2),
   crim_othr_hrs           number(10,2),
   pto_hrs                 number(10,2),
   ino_hrs                 number(10,2),
   brdi_hrs                number(10,2),
   sedev_hrs               number(10,2),
   dna_hrs                 number(10,2),
   dna_samples_cnt         number(6),
   sup_front_line_hrs      number(10,2),
   admin_hrs               number(10,2),
   cpic_justin_hrs         number(10,2),
   cpic_ja_hrs             number(10,2),
   sir_hrs                 number(10,2),
   pio_io_hrs              number(10,2),
   sup_duties_n_front_line number(10,2),
   crn_pnls                number(6),
   crn_admn_hrs            number(10,2),
   crn_jrs_smnd            number(6),
   veh_mgnt_hrs            number(10,2)
);

create table courts.sheriff_srvces_hours (
   crt_loc_id                  number(6),
   month                       date,
   supervisor_yn               varchar2(1 byte),
   ca_reg_reg_hrs              number(10,2),
   ca_reg_ot_hrs               number(10,2),
   ca_hsm_reg_hrs              number(10,2),
   ca_hsm_ot_hrs               number(10,2),
   scv_jy_shrf_reg_hrs         number(10,2),
   scv_jy_shrf_ot_hrs          number(10,2),
   scv_jy_hsm_reg_hrs          number(10,2),
   scv_jy_hsm_ot_hrs           number(10,2),
   scv_delib_reg_hrs           number(10,2),
   scv_delib_ot_hrs            number(10,2),
   scv_delib_hsm_reg_hrs       number(10,2),
   scv_delib_hsm_ot_hrs        number(10,2),
   scv_nj_shrf_reg_hrs         number(10,2),
   scv_nj_shrf_ot_hrs          number(10,2),
   scv_nj_hsm_reg_hrs          number(10,2),
   scv_nj_hsm_ot_hrs           number(10,2),
   scr_jy_shrf_reg_hrs         number(10,2),
   scr_jy_shrf_ot_hrs          number(10,2),
   scr_jy_hsm_reg_hrs          number(10,2),
   scr_jy_hsm_ot_hrs           number(10,2),
   scr_delib_reg_hrs           number(10,2),
   scr_delib_ot_hrs            number(10,2),
   scr_delib_hsm_reg_hrs       number(10,2),
   scr_delib_hsm_ot_hrs        number(10,2),
   scr_nj_shrf_reg_hrs         number(10,2),
   scr_nj_shrf_ot_hrs          number(10,2),
   scr_nj_hsm_reg_hrs          number(10,2),
   scr_nj_hsm_ot_hrs           number(10,2),
   scvf_shrf_reg_hrs           number(10,2),
   scvf_shrf_ot_hrs            number(10,2),
   scvf_hsm_reg_hrs            number(10,2),
   scvf_hsm_ot_hrs             number(10,2),
   pcvf_shrf_reg_hrs           number(10,2),
   pcvf_shrf_ot_hrs            number(10,2),
   pcvf_hsm_reg_hrs            number(10,2),
   pcvf_hsm_ot_hrs             number(10,2),
   pcvs_shrf_reg_hrs           number(10,2),
   pcvs_shrf_ot_hrs            number(10,2),
   pcvs_hsm_reg_hrs            number(10,2),
   pcvs_hsm_ot_hrs             number(10,2),
   pcra_shrf_reg_hrs           number(10,2),
   pcra_shrf_ot_hrs            number(10,2),
   pcra_hsm_reg_hrs            number(10,2),
   pcra_hsm_ot_hrs             number(10,2),
   pcry_shrf_reg_hrs           number(10,2),
   pcry_shrf_ot_hrs            number(10,2),
   pcry_hsm_reg_hrs            number(10,2),
   pcry_hsm_ot_hrs             number(10,2),
   othr_shrf_reg_hrs           number(10,2),
   othr_shrf_ot_hrs            number(10,2),
   othr_hsm_reg_hrs            number(10,2),
   othr_hsm_ot_hrs             number(10,2),
   rvr_shrf_reg_hrs            number(10,2),
   rvr_shrf_ot_hrs             number(10,2),
   rvr_hsm_reg_hrs             number(10,2),
   rvr_hsm_ot_hrs              number(10,2),
   sg_staff_reg_hrs            number(10,2),
   sg_staff_ot_hrs             number(10,2),
   sg_hsm_reg_hrs              number(10,2),
   sg_hsm_ot_hrs               number(10,2),
   crnr_shrf_reg_hrs           number(10,2),
   crnr_shrf_ot_hrs            number(10,2),
   crnr_hsm_reg_hrs            number(10,2),
   crnr_hsm_ot_hrs             number(10,2),
   vc_staff_reg_hrs            number(10,2),
   vc_staff_ot_hrs             number(10,2),
   vc_hsm_reg_hrs              number(10,2),
   vc_hsm_ot_hrs               number(10,2),
   hld_shrf_reg_hrs            number(10,2),
   hld_shrf_ot_hrs             number(10,2),
   grd_esc_reg_hrs_l1          number(10,2),
   grd_esc_ot_hrs_l1           number(10,2),
   grd_esc_reg_hrs_l2          number(10,2),
   grd_esc_ot_hrs_l2           number(10,2),
   grd_esc_reg_hrs_l3          number(10,2),
   grd_esc_ot_hrs_l3           number(10,2),
   air_esc_reg_hrs_l1          number(10,2),
   air_esc_ot_hrs_l1           number(10,2),
   air_esc_reg_hrs_l2          number(10,2),
   air_esc_ot_hrs_l2           number(10,2),
   air_esc_reg_hrs_l3          number(10,2),
   air_esc_ot_hrs_l3           number(10,2),
   ccrt_reg_hrs                number(10,2),
   ccrt_ot_hrs                 number(10,2),
   cvf_warr_reg_hrs            number(10,2),
   cvf_warr_ot_hrs             number(10,2),
   cvf_crtord_reg_hrs          number(10,2),
   cvf_crtord_ot_hrs           number(10,2),
   cvf_docs_reg_hrs            number(10,2),
   cvf_docs_ot_hrs             number(10,2),
   cvf_othr_reg_hrs            number(10,2),
   cvf_othr_ot_hrs             number(10,2),
   crim_warr_reg_hrs           number(10,2),
   crim_warr_ot_hrs            number(10,2),
   crim_crtord_reg_hrs         number(10,2),
   crim_crtord_ot_hrs          number(10,2),
   crim_docs_reg_hrs           number(10,2),
   crim_docs_ot_hrs            number(10,2),
   crim_othr_reg_hrs           number(10,2),
   crim_othr_ot_hrs            number(10,2),
   pto_reg_hrs                 number(10,2),
   pto_ot_hrs                  number(10,2),
   ino_reg_hrs                 number(10,2),
   ino_ot_hrs                  number(10,2),
   brdi_reg_hrs                number(10,2),
   brdi_ot_hrs                 number(10,2),
   dna_reg_hrs                 number(10,2),
   dna_ot_hrs                  number(10,2),
   admin_reg_hrs               number(10,2),
   admin_ot_hrs                number(10,2),
   cpic_justin_reg_hrs         number(10,2),
   cpic_justin_ot_hrs          number(10,2),
   cpic_ja_reg_hrs             number(10,2),
   cpic_ja_ot_hrs              number(10,2),
   sir_reg_hrs                 number(10,2),
   sir_ot_hrs                  number(10,2),
   veh_mgnt_reg_hrs            number(10,2),
   veh_mgnt_ot_hrs             number(10,2),
   sup_duties_n_front_line_reg number(10,2),
   sup_duties_n_front_line_ot  number(10,2),
   pio_io_reg_hrs              number(10,2),
   pio_io_ot_hrs               number(10,2),
   create_date                 date,
   created_by                  varchar2(30 byte),
   update_date                 date,
   updated_by                  varchar2(30 byte)
);