name: Build Dotnet
description: Builds the .NET solution with quality gates

inputs:
  working_directory:
    description: The working directory where the code will be built.
    required: true
  dotnet_version:
    description: The .NET version that will be used.
    required: true

runs:
  using: composite

  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Restore dependencies
      run: dotnet restore unified.slnx
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Build Solution
      run: dotnet build unified.slnx --configuration Release --no-restore
      shell: bash
      working-directory: ${{ inputs.working_directory }}
