using System.Data.Common;
using System.Text.Json;
using Audit.Core;
using Audit.EntityFramework;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Extensions.Options;
using Unified.Common.Audit;
using Unified.Db;
using Unified.Db.Models;

namespace Unified.Audit.Interceptors;

/// <summary>
/// Audit.NET data provider that persists captured SaveChanges events as <see cref="AuditRecord"/>
/// rows via a dedicated <see cref="AuditRecordDbContext"/> instance, sharing the audited context's
/// connection and (owned) transaction — see <see cref="AuditTransactionInterceptor"/>.
///
/// Using a separate DbContext means writing audit records never re-triggers the interceptors
/// registered on the audited context (no recursive audit capture, no re-entrant save rules).
///
/// Because <see cref="EntityFrameworkEvent.Entries"/> is populated by Audit.NET after the
/// underlying SaveChanges completes, primary keys and foreign keys generated by the database are
/// already resolved — no manual bookkeeping is required to reconcile temporary keys.
/// </summary>
public sealed class AuditRecordDataProvider(
    Func<DbConnection, DbContextOptions<AuditRecordDbContext>> auditDbContextOptionsFactory,
    ICurrentActorResolver actorResolver,
    IHttpContextAccessor httpContextAccessor,
    IOptions<AuditRecordInterceptorOptions> options
) : AuditDataProvider
{
    private static readonly JsonSerializerOptions SerializerOptions = new(JsonSerializerDefaults.Web);

    private readonly AuditRecordInterceptorOptions _options = options.Value;

    public override object InsertEvent(AuditEvent auditEvent) => InsertEventAsync(auditEvent).GetAwaiter().GetResult();

    public override async Task<object> InsertEventAsync(
        AuditEvent auditEvent,
        CancellationToken cancellationToken = default
    )
    {
        var efEvent = auditEvent.GetEntityFrameworkEvent();
        var mainContext = efEvent?.GetDbContext();
        var records = efEvent is null ? [] : BuildAuditRecords(efEvent, auditEvent);

        if (mainContext is null || records.Count == 0)
        {
            return records;
        }

        var auditDbContextOptions = auditDbContextOptionsFactory(mainContext.Database.GetDbConnection());
        await using var auditDbContext = new AuditRecordDbContext(auditDbContextOptions);

        var transaction = mainContext.Database.CurrentTransaction;
        if (transaction is not null)
        {
            await auditDbContext.Database.UseTransactionAsync(transaction.GetDbTransaction(), cancellationToken);
        }

        auditDbContext.AuditRecords.AddRange(records);
        await auditDbContext.SaveChangesAsync(cancellationToken);

        return records;
    }

    private List<AuditRecord> BuildAuditRecords(EntityFrameworkEvent efEvent, AuditEvent auditEvent)
    {
        var actor = actorResolver.Resolve();
        var correlationId = ResolveCorrelationId(auditEvent);
        var records = new List<AuditRecord>();

        // The audit table itself is excluded from capture entirely via Audit.NET's own
        // configuration (see AuditModule.UseAuditModule), so every entry here is a real audited entity.
        foreach (var entry in efEvent.Entries)
        {
            records.Add(BuildAuditRecord(entry, entry.GetEntry().Metadata, actor, correlationId));
        }

        return records;
    }

    private AuditRecord BuildAuditRecord(
        EventEntry entry,
        IEntityType entityType,
        CurrentActor actor,
        string? correlationId
    )
    {
        var changedColumns = entry
            .Changes?.Select(change => change.ColumnName)
            .Where(columnName => !ShouldExclude(entityType, columnName))
            .ToArray();

        return new AuditRecord
        {
            OccurredOn = DateTimeOffset.UtcNow,
            ActorUserId = actor.ActorUserId,
            ActorName = actor.ActorName,
            Action = MapAction(entry.Action),
            EntityType = entityType.ClrType.Name,
            TableName = entry.Table,
            KeyValues = JsonSerializer.Serialize(entry.PrimaryKey, SerializerOptions),
            OldValues = BuildValues(entry, entityType, oldValues: true),
            NewValues = BuildValues(entry, entityType, oldValues: false),
            ChangedColumns = changedColumns is { Length: > 0 } ? changedColumns : null,
            SourceModule = _options.SourceModule,
            CorrelationId = correlationId,
        };
    }

    // entry.Action reflects the state EF Core captured pre-save (Insert/Update/Delete); the live
    // EntityEntry.State is reset by the ChangeTracker immediately after a successful save, so it
    // can't be used here (this runs post-save).
    private string? BuildValues(EventEntry entry, IEntityType entityType, bool oldValues)
    {
        Dictionary<string, object?> values = [];

        if (string.Equals(entry.Action, "Update", StringComparison.Ordinal))
        {
            foreach (var change in entry.Changes ?? [])
            {
                if (ShouldExclude(entityType, change.ColumnName))
                {
                    continue;
                }

                values[change.ColumnName] = oldValues ? change.OriginalValue : change.NewValue;
            }
        }
        else
        {
            var isInsert = string.Equals(entry.Action, "Insert", StringComparison.Ordinal);
            if ((isInsert && oldValues) || (!isInsert && !oldValues))
            {
                return null;
            }

            foreach (var (columnName, value) in entry.ColumnValues)
            {
                if (ShouldExclude(entityType, columnName))
                {
                    continue;
                }

                values[columnName] = value;
            }
        }

        return values.Count == 0 ? null : JsonSerializer.Serialize(values, SerializerOptions);
    }

    private bool ShouldExclude(IEntityType entityType, string propertyName)
    {
        var property = entityType.FindProperty(propertyName);
        return property is not null && AuditPropertyExclusion.ShouldExclude(property, _options);
    }

    private static string MapAction(string action) =>
        action switch
        {
            "Insert" => "Added",
            "Update" => "Modified",
            "Delete" => "Deleted",
            _ => action,
        };

    private string? ResolveCorrelationId(AuditEvent auditEvent)
    {
        var httpContext = httpContextAccessor.HttpContext;
        if (httpContext is null)
        {
            // No HTTP request (e.g. a background job) - fall back to Audit.NET's own distributed
            // tracing capture (Audit.Core.Configuration.IncludeActivityTrace, set in AuditModule).
            return auditEvent.Activity?.TraceId;
        }

        foreach (var headerName in _options.CorrelationIdHeaderNames)
        {
            if (httpContext.Request.Headers.TryGetValue(headerName, out var value) && !string.IsNullOrWhiteSpace(value))
            {
                return value.ToString();
            }
        }

        // Falls back to ASP.NET Core's per-request identifier, matching the traceId GlobalExceptionHandler returns to clients.
        return httpContext.TraceIdentifier;
    }
}
