name: Publish Dotnet

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - "db/**"
      - "docker/api/**"
      - ".github/workflows/cd-dotnet.yml"

  workflow_dispatch:

env:
  IMAGE_NAME: api
  GITHUB_IMAGE_REPO: ghcr.io/bcgov/unified-scheduling
  GITOPS_LICENCE_PLATE: a94b15
  GITOPS_BRANCH: develop

permissions:
  id-token: write
  packages: write

jobs:
  build:
    name: Build and Push API Image
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.short_sha.outputs.SHORT_SHA }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Log in to the GHCR
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short SHA
        id: short_sha
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup Image Metadata
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: |
            ${{ env.GITHUB_IMAGE_REPO }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.short_sha.outputs.SHORT_SHA }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          push: true
          context: .
          file: ./docker/api/Dockerfile.release
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  update-gitops-dev:
    name: Update GitOps Dev
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Update ArgoCD Kustomize Repo with new Image
        uses: ./.github/workflows/actions/update-argo-kustomize
        with:
          licence_plate: ${{ env.GITOPS_LICENCE_PLATE }}
          gitops_branch: ${{ env.GITOPS_BRANCH }}
          gitops_gh_token: ${{ secrets.GITOPS_GH_TOKEN  }}
          image_name: unified-scheduling-api
          new_image: ${{ env.GITHUB_IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ needs.build.outputs.short_sha }}
          kustomize_path: services/unified-scheduling/overlays/dev
